# Generated by Django 4.1 on 2022-09-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
