# Generated by Django 4.1 on 2022-09-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_name_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost',
            new_name='post',
        ),
    ]
