# Generated by Django 4.1 on 2022-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_blogpost_delete_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
