# Generated by Django 4.1 on 2022-10-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_blogpost_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
