# Generated by Django 4.1 on 2022-10-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blogpost_delete_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commented_post',
        ),
    ]
