# Generated by Django 4.1 on 2022-10-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_rename_post_comment_commented_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_post',
            new_name='post',
        ),
    ]
