# Generated by Django 4.1 on 2022-10-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_remove_comment_parent_commentreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
