# Generated by Django 4.1 on 2022-10-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_remove_comment_parent_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blogs.comment'),
        ),
    ]
