# Generated by Django 4.1 on 2022-10-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_alter_commentreply_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
